# Generated by Django 2.2 on 2020-08-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrename',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='director',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=85, unique=True, verbose_name='username'),
        ),
    ]
