# Generated by Django 3.1 on 2020-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
    ]
